[package]
name = "keyup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo-console = "0.2.1"
wasm-bindgen = "0.2.78"
yew = "0.19.3"
